### PR TITLE
Fix escaping with unnecessary translation string

### LINKED ISSUE #6: Error on translation string
On https://github.com/qstudio/advanced-custom-fields-number-slider/blob/master/number-slider-v4.php#L152 there is no need to make this translatable, as it can be seen on https://translate.wordpress.org/projects/wp-plugins/advanced-custom-fields-number-slider/stable/pt/default/?filters%5Boriginal_id%5D=13036654

Could be just escaped with no gettext.

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Fixes #6

### CODE REVIEW

**Comment by qstudio** [comment]
> Thank you for this great plugin <3

Thanks!.. but really, it's pretty old and I wondered if it got much use at all - and perhaps the JS Slider library used needs to be updated or replaced with something more modern - what do you think?

**Comment by pedro-mendonca** [comment]
Well, that's a whole new discussion :)
I've used it, one thing I would add to it an option to turn the slider in a range selector:
|---------{min}-------------------------{max}---------------------------------|

**Comment by qstudio** [comment]
Range would be nice... why not.. but does ACF now include some sort of number range field with a slider?

https://www.advancedcustomfields.com/resources/range/

**Comment by qstudio** [comment]
actually.. that looks pretty much exactly like what this plugin does :)

**Pull request merged**
